quarkus:
  application:
    name: finanz-app
  http:
    port: 8080
    root-path: /api/v1
  datasource:
    db-kind: h2
    username: sa
    password:
    jdbc:
      url: jdbc:h2:file:./target/h2/finanz_db;AUTO_SERVER=true
      max-size: 20
      acquisition-timeout: 30
      min-size: 1
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
    log:
      sql: true
      format-sql: true
      bind-parameters: true
  live-reload:
    instrumentation: true