"%dev":
  quarkus:
    application:
      name: finanz-app
    http:
      port: 8080
      root-path: /api/v1
      auth:
        policy:
          role-policy1:
            roles-allowed: ADMIN
          role-policy2:
            roles-allowed: ADMIN, USER
        permission:
          auth:
            paths: auth/*
            policy: permit
            methods: POST
          roles:
            paths: auth/user
            policy: role-policy2
            methods: GET
      cors:
        enabled: true
        origins: "http://localhost:4200"
        methods: "GET, POST, PUT, DELETE, OPTIONS"
    datasource:
      db-kind: h2
      username: sa
      password:
      jdbc:
        url: jdbc:h2:file:./target/h2/finanz_db;AUTO_SERVER=true
        max-size: 20
        acquisition-timeout: 30
        min-size: 1
    hibernate-orm:
      schema-management:
        strategy: drop-and-create
      log:
        sql: true
        format-sql: true
        bind-parameters: true
    live-reload:
      instrumentation: true
  mp:
    jwt:
      verify:
        issuer: ${JWT_ISSUER}
        publickey:
          location: src/main/resources/keys/publicKey.pem

  smallrye:
    jwt:
      sign:
        key:
          location: src/main/resources/keys/privateKey.pem
      encrypt:
        key:
          location: src/main/resources/keys/publicKey.pem

#smallrye.jwt.sign.key=${private.key.from.vault}
#smallrye.jwt.encrypt.key=${public.key.from.vault}